// Generated by CoffeeScript 1.6.3
(function() {
  var YParser, bnf, generator, node, parser, test_str, _i, _len, _ref;

  YParser = require("yparser");

  bnf = "id = id ;\nint = int ;\nspace = anyspace+ ;\n\nmain :: [space? token]* space? eof\n  ;\n\ntoken ::\n    id:id\n  | int(toNumber):int\n  ;\n";

  generator = new YParser.Generator(bnf);

  parser = generator.generate();

  test_str = "toto titi 42\ttata\ntutu 55 hey ho";

  parser.loadString(test_str);

  parser.init();

  parser.parse() || parser.error();

  _ref = parser.ast.nodes;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    node = _ref[_i];
    console.log(JSON.stringify(node));
  }

}).call(this);
